#!/usr/bin/env python3
"""blind_sort.py — blind rank-sort of a rung ladder, on an instrument first shown able to fail.

WHY THIS EXISTS. `tests/test_displeasure_universal.py` is a string lint: block length, three
bullets, an italic anchor, banned phrases, plus `rungs.rung_at` (a float->index resolver that never
reads block text). Measured 2026-09-07: reversing all twelve blocks — rung 1 holding rung 12's text
— passes 4 of 4. The suite has ZERO ordering sensitivity, so a green build is not ordering evidence.
This is the missing instrument.

THREE ARMS, and the order of belief matters. From `basis_probe.py`'s docstring, earned the hard
way: *a scorer that can only produce chance is indistinguishable from a null result, which is the
most expensive kind of bug an experiment can have.*

    scramble  NEGATIVE control. Sentences are redealt across all twelve blocks, destroying the
              ladder while preserving register and vocabulary. rho MUST collapse toward 0. If it
              does not, the panel is scoring prose register rather than order, and no number from
              this harness means anything.
    poetic    POSITIVE control. The superseded v1 text in
              staging/DISPLEASURE-poetic-superseded-2026-09-06.md, independently blind-sorted at
              mean rho 0.986 (3 sorters, 3 shuffles, wf_5187996a-5ff). rho MUST come back clearly
              positive. If it does not, this PANEL cannot read this kind of ladder, and a low score
              on the current text would be an instrument failure misread as a ladder failure.
    current   THE TEST. The twelve universalized blocks in src/engine/rung_blocks.py.

THE 0.986 IS NOT A TARGET. It was measured by Claude-family subagents; this panel is local Ollama.
Cross-substrate, the absolute number is not expected to reproduce and matching it was never the
bar. What the positive control establishes is the panel's SENSITIVITY — that it can tell an ordered
ladder from a scrambled one. Only a panel that has demonstrated that gets to be believed about the
current text.

THREE MODEL FAMILIES, not three samples of one. On 2026-09-07 three "independent" rewriters were
traced to one model sampled twice plus a peer reading their brief verbatim. The prior 0.986 carries
its own warning in the same words: *THIS IS ONE MODEL FAMILY ... the previous ladder ALSO had three
agreeing sorters, which is exactly how it was found to be broken rather than how it was confirmed.*

    python tests/blind_sort.py --dry              # build stimuli, print one, make no model calls
    python tests/blind_sort.py --arm poetic       # one arm
    python tests/blind_sort.py                    # all three arms, 3 judges x 3 permutations

Local Ollama only — no key, no cost. Results append to tests/blind_sort_results.jsonl.

NOT named test_*.py on purpose: tests/run_all.py DISCOVERS suites, and this makes ~27 model calls.
Same reason basis_probe.py and coherence_probe.py sit here under their own names.
"""
import argparse
import json
import os
import random
import re
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

DROP = [0]                       # set from --drop; recorded on every row so runs cannot be conflated
LABELS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"  # slots; the judge never sees a number that could imply order
# Three FAMILIES — Qwen, Mistral, Gemma. Not three samples of one lineage.
#
# The 31b/32b tier was the first choice and was abandoned, measured rather than assumed: a 19 GB
# cold load stalled the first run past ten minutes with no model resident in `ollama ps`. At this
# tier every judge answers a 9.4k-char ordering prompt in ~15 s and parses clean. The trade is
# real and stated: these are weaker readers than the 32b tier and MUCH weaker than the
# Claude-family subagents that produced the 0.986. That is precisely why the `poetic` positive
# control gates the run — if this panel cannot recover a ladder known to be ordered, its verdict
# on the current text is worthless and must not be reported as a ladder defect.
JUDGES = ["qwen2.5:14b", "mistral-nemo:12b", "gemma4:e4b"]
PERMUTATION_SEEDS = [7, 41, 103]
POETIC_PATH = os.path.join(REPO, "staging", "DISPLEASURE-poetic-superseded-2026-09-06.md")
RESULTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "blind_sort_results.jsonl")


# --------------------------------------------------------------------------- ladders

def load_current(path="DISPLEASURE"):
    """The live blocks for `path`. Imported, not re-read from the doc, so this scores what the
    ENGINE would actually serve — the doc and the module have drifted apart before, and on
    2026-09-07 `rung_blocks.py` was regenerated by a PARALLEL SESSION at 13:41 while a sort of it
    was in flight. Exactly one block had changed (DISPLEASURE rung 6, 839 -> 843 chars, `anger` ->
    `hostility`); the other eleven were byte-identical. Caught by mtime and length, not by git —
    the file is tracked but the drift was inside a working-tree edit. RE-SORT rather than caveat:
    the run is nine calls."""
    from src.engine.rung_blocks import BLOCKS
    if path not in BLOCKS:
        raise AssertionError("no path %r in rung_blocks; have %s" % (path, list(BLOCKS)))
    return dict(BLOCKS[path])


def load_poetic():
    """Parse the superseded v1 blocks out of the staging doc.

    The `**[State: name]**` line is STRIPPED — it names the rung, which is the whole thing a blind
    sort must not see. The prior run's own protocol line says the same: *blocks stripped of their
    rung names*."""
    text = open(POETIC_PATH, encoding="utf-8").read()
    blocks = {}
    # sections run `### N — name` up to the next `###` or `##`
    for m in re.finditer(r"^###\s+(\d{1,2})\s+—\s+\S+\s*$", text, re.MULTILINE):
        idx = int(m.group(1))
        if not 1 <= idx <= 12:
            continue
        start = m.end()
        nxt = re.search(r"^#{2,3}\s", text[start:], re.MULTILINE)
        body = text[start:start + nxt.start()] if nxt else text[start:]
        body = re.sub(r"^\s*\*\*\[State:[^\]]*\]\*\*\s*$", "", body, flags=re.MULTILINE)
        blocks[idx] = body.strip()
    if sorted(blocks) != list(range(1, 13)):
        raise AssertionError("poetic parse got rungs %s, wanted 1..12" % sorted(blocks))
    return blocks


def make_scramble(ladder, seed):
    """NEGATIVE control: redeal sentences across all twelve blocks.

    `seed` IS REQUIRED, and it was not in the first version. That version defaulted to a single
    fixed seed, so all nine runs scored THE SAME scrambled ladder — nine reads of one draw from the
    null, not nine draws. It returned mean rho -0.427, which looks like a systematic anti-
    correlation and is nothing of the kind: one draw can sit anywhere. A mean over correlated reads
    of a single realisation is not an estimate of the null. Measured 2026-09-07, and it is the same
    defect as learnings/2026-09-06-the-criterion-passed-four-times-on-a-population-of-one.

    Register, vocabulary and the four-part shape survive; the ladder does not. A panel that still
    reports a strong rho here is ranking how the prose SOUNDS, not what it says — which is the
    exact failure the prior session hit from the other direction (judges scoring agitation as
    depth, and prose measuredness as composure)."""
    n = len(ladder)
    rng = random.Random(seed)
    pool = []
    for i in range(1, n + 1):
        pool += [s for s in re.split(r"(?<=[.!?])\s+", ladder[i]) if s.strip()]
    rng.shuffle(pool)
    sizes = [len(re.split(r"(?<=[.!?])\s+", ladder[i])) for i in range(1, n + 1)]
    out, at = {}, 0
    for i in range(1, n + 1):
        out[i] = " ".join(pool[at:at + sizes[i - 1]])
        at += sizes[i - 1]
    return out


def check_no_name_leak(ladder, path="DISPLEASURE"):
    """A block naming ANY band on its own ladder hands the sort away. Checked, not assumed.

    This found DISPLEASURE rung 6 opening *"The anger is fully formed"* — `anger` being rung 7's
    band name — on 2026-09-07. It is now `hostility` and the ladder is clean."""
    from src.engine.rung_blocks import BANDS
    names = [n for _, _, n in BANDS[path]]
    leaks = []
    for i, text in ladder.items():
        low = text.lower()
        for n in names:
            if re.search(r"\b%s\b" % re.escape(n), low):
                leaks.append((i, n))
    return leaks


# --------------------------------------------------------------------------- scoring

def spearman(order_true, order_got):
    """rho over ranks. n=12 with no ties, so the shortcut form is exact."""
    n = len(order_true)
    rank = {v: i for i, v in enumerate(order_got)}
    d2 = sum((i - rank[v]) ** 2 for i, v in enumerate(order_true))
    return 1.0 - (6.0 * d2) / (n * (n * n - 1))


def exact_positions(order_true, order_got):
    return sum(1 for a, b in zip(order_true, order_got) if a == b)


# --------------------------------------------------------------------------- the ask

def sort_prompt(presented):
    """`presented` is [(label, text), ...] in permuted order.

    The axis is NOT named. The prior sort asked only "faintest to strongest" and one sorter
    recovered the control axis unprompted — naming it here would hand over the answer and convert a
    recovery result into a compliance result.

    THE COUNT IS DERIVED, NEVER SPELLED OUT. This prompt hard-coded the word "twelve" in three
    places while the harness had already been generalised to any n. Every RECEPTIVITY run on
    2026-09-07 therefore told the judge "Below are twelve descriptions ... put all twelve in order
    ... answer with the twelve letters" while showing it ELEVEN blocks, and those numbers were
    posted to the board before the defect was found. DISPLEASURE, at n=12, was unaffected — which
    is precisely what made the comparison between the two paths worthless: one arm had a correct
    prompt and the other did not.
    """
    n = len(presented)
    body = "\n\n".join("[%s]\n%s" % (lab, txt) for lab, txt in presented)
    return (
        "Below are %d descriptions of a person's inner state. They belong to ONE progression, "
        "from the mildest state at one end to the most extreme at the other. They are shown to you "
        "in scrambled order.\n\n"
        "%s\n\n"
        "Put all %d in order, from MILDEST to MOST EXTREME.\n\n"
        "Answer with the %d letters separated by commas, mildest first, and nothing else. "
        "Example format: C, A, J, ...\n"
        "Use every letter exactly once." % (n, body, n, n))


def parse_order(reply, n=12):
    """Take letters in the order given, first occurrence wins. Returns None unless ALL `n` labels
    are present — a partial answer is dropped rather than padded, because padding would invent
    order the judge did not supply and quietly pull rho toward the truth.

    `n` is required to be honoured, not decorative: this function briefly carried an `n` parameter
    while its body still hard-coded 12 and the label class `[A-L]`. Against an 11-rung ladder that
    silently rejected EVERY valid reply (11 != 12) and would have reported the arm as unscorable —
    a wrong answer that looks like a model failure. Caught by a two-line assertion, not by reading
    it."""
    allowed = set(LABELS[:n])
    seen = []
    for ch in re.findall(r"\b([A-Z])\b", (reply or "").upper()):
        if ch in allowed and ch not in seen:
            seen.append(ch)
    return seen if len(seen) == n else None


def _ollama(model, prompt, seed):
    # think=False: gemma4 is a thinking model and its hidden trace otherwise eats the budget and
    # returns an empty string. Measured in basis_probe.py (55 of 162 replies empty) and already
    # documented in scripts/direct.py. num_predict is 400 here, not 200 — twelve comma-separated
    # labels plus any preamble does not fit in 200.
    body = json.dumps({"model": model, "prompt": prompt, "stream": False, "think": False,
                       "options": {"temperature": 0.0, "seed": seed, "num_predict": 400}}).encode()
    req = urllib.request.Request("http://localhost:11434/api/generate", data=body,
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=600) as r:
        return json.load(r).get("response", "")


# --------------------------------------------------------------------------- run

def run_arm(arm, ladder, judges, dry=False, base_for_scramble=None, path="DISPLEASURE"):
    rows = []
    leaks = check_no_name_leak(ladder, path)
    if leaks:
        print("  WARNING  band name appears in its own block: %s" % leaks)

    for seed in PERMUTATION_SEEDS:
        # A FRESH scramble per seed, so the three seeds are three independent draws from the null
        # rather than one draw read three times. Only the scramble arm re-derives here; the real
        # ladders are fixed artifacts and must not be regenerated per seed.
        arm_ladder = make_scramble(base_for_scramble, seed) if arm == "scramble" else ladder

        n = len(arm_ladder)
        rng = random.Random(seed)
        rungs = list(range(1, n + 1))
        rng.shuffle(rungs)
        # slot j (label LABELS[j]) holds rung rungs[j]
        presented = [(LABELS[j], arm_ladder[rungs[j]]) for j in range(n)]
        truth = [LABELS[rungs.index(r)] for r in range(1, n + 1)]   # labels, mildest -> most extreme

        if dry:
            print("\n--- arm=%s seed=%d ---" % (arm, seed))
            print("truth (mild->extreme): %s" % ", ".join(truth))
            print(sort_prompt(presented)[:1200] + "\n...[truncated]")
            return rows

        for judge in judges:
            reply = _ollama(judge, sort_prompt(presented), seed=seed)
            got = parse_order(reply, n)
            if got is None:
                print("  DROP  %-26s seed=%-4d unparseable, need %d labels (%d chars)"
                      % (judge, seed, n, len(reply or "")))
                rows.append({"arm": arm, "judge": judge, "seed": seed, "rho": None,
                             "exact": None, "raw": (reply or "").strip()[:300]})
                continue
            rho = spearman(truth, got)
            ex = exact_positions(truth, got)
            print("  %-26s seed=%-4d rho=%+.3f  exact=%2d/%d" % (judge, seed, rho, ex, n))
            rows.append({"arm": arm, "path": path, "drop": DROP[0], "judge": judge, "seed": seed, "rho": rho, "exact": ex,
                         "truth": truth, "got": got, "raw": (reply or "").strip()[:300]})
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", default="all", choices=["all", "scramble", "poetic", "current"])
    ap.add_argument("--path", default="DISPLEASURE",
                    help="which ladder in rung_blocks.BLOCKS to score. `poetic` is DISPLEASURE-only "
                         "(it is that path's superseded v1) and is skipped for any other path.")
    ap.add_argument("--judges", default=",".join(JUDGES))
    ap.add_argument("--dry", action="store_true")
    ap.add_argument("--drop", type=int, default=0,
                    help="TRUE leave-one-out: remove this rung and re-sort the remaining n-1 as a "
                         "fresh task. Distinct from an ANALYTIC leave-one-out (deleting the rung "
                         "from an answer the judge gave while seeing all n) — that only screens, "
                         "because the dropped block was still on the page influencing every other "
                         "placement. ALWAYS pair a --drop run with a control drop of a rung the "
                         "screening pass says costs nothing: a shorter ladder has fewer pairs to "
                         "misorder, so rho can rise from LENGTH alone. Without that control, "
                         "'removing rung X tightened the ladder' is unfalsifiable.")
    a = ap.parse_args()
    judges = [j.strip() for j in a.judges.split(",") if j.strip()]
    DROP[0] = a.drop

    current = load_current(a.path)
    dropped_note = ""
    if a.drop:
        if a.drop not in current:
            raise SystemExit("--drop %d not in %s (have %s)" % (a.drop, a.path, sorted(current)))
        kept = [i for i in sorted(current) if i != a.drop]
        current = {new: current[old] for new, old in enumerate(kept, start=1)}
        dropped_note = " [DROPPED rung %d, %d remain]" % (a.drop, len(current))
    ladders = {
        "scramble": make_scramble(current, PERMUTATION_SEEDS[0]),   # placeholder; re-derived per seed
        "poetic": load_poetic(),
        "current": current,
    }
    arms = ["scramble", "poetic", "current"] if a.arm == "all" else [a.arm]
    if a.path != "DISPLEASURE" and "poetic" in arms:
        arms.remove("poetic")   # the poetic control is DISPLEASURE's own superseded text

    all_rows = []
    for arm in arms:
        print("\n=== ARM: %s ===" % arm)
        rows = run_arm(arm, ladders[arm], judges, dry=a.dry, base_for_scramble=current,
                       path=a.path)
        all_rows += rows
        scored = [r["rho"] for r in rows if r["rho"] is not None]
        if scored:
            print("  MEAN rho = %+.3f   (n=%d of %d scored)"
                  % (sum(scored) / len(scored), len(scored), len(rows)))

    if a.dry:
        return

    with open(RESULTS, "a", encoding="utf-8") as f:
        for r in all_rows:
            f.write(json.dumps(r) + "\n")

    print("\n=== SUMMARY ===")
    for arm in arms:
        scored = [r["rho"] for r in all_rows if r["arm"] == arm and r["rho"] is not None]
        if scored:
            print("  %-9s mean rho %+.3f   n=%d" % (arm, sum(scored) / len(scored), len(scored)))
        else:
            print("  %-9s NO SCORED RUNS" % arm)
    print("\nwrote %s" % RESULTS)


if __name__ == "__main__":
    main()
