"""test_canon_digest.py — the digest must equal the DB it digests.

`canon-ledger.md` was described as GENERATED in eight tracked files and generated by nothing until
2026-08-24 — `docs/orchestration.md`, `docs/design.md`, `CLAUDE.md`'s canon/process split, the
showrunner agent, and the template's own header all promised a producer that did not exist. This
repo's dominant defect class: specified, described as built, reaching nothing (`verdict_for`,
`bible.drifted()`, `formative.*`).

So the guard here is not "does it run" — it is **does the digest agree with its source**, because a
digest that quietly under-reports is worse than none: it is a reading surface people trust.
"""
import io
import os
import sqlite3
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "scripts"))

import canon_digest                                             # noqa: E402
from src.engine.db import connect                               # noqa: E402

_FAILS = []


def check(name, ok, detail=""):
    print("  %s  %s%s" % ("PASS" if ok else "FAIL", name, "" if ok else "  -> %s" % detail))
    if not ok:
        _FAILS.append(name)


def _fixture_db(tmp):
    """A run with events, scenes and a snapshot — invented, per CLAUDE.md hard rule 1."""
    db = os.path.join(tmp, "d.db")
    con = connect(db)
    con.execute("INSERT INTO runs(run_id, created_at, status, config) VALUES(?,?,?,?)",
                ("r1", "2026-01-01", "parked", "{}"))
    for i, (typ, actor) in enumerate([("betray", "a"), ("threat", "b"), ("care", "a")]):
        con.execute("INSERT INTO events(run_id, turn, caused_at, effective_at, type, actor, target, "
                    "location, visibility, payload) VALUES(?,?,?,?,?,?,?,?,?,?)",
                    ("r1", i, "t", "t", typ, actor, "b", "yard", "public",
                     '{"text": "something happened", "durability": "durable"}'))
    con.execute("INSERT INTO scenes(run_id, scene_no, label, pov, start_turn, end_turn) "
                "VALUES(?,?,?,?,?,?)", ("r1", 1, "the yard", "a", 0, 2))
    con.execute("INSERT INTO snapshots(run_id, as_of_turn, kind, key, value) VALUES(?,?,?,?,?)",
                ("r1", 2, "agents", "a", '{"life_status": "alive"}'))
    con.commit()
    return db, con


def test_every_event_reaches_the_digest():
    """The count in the text must equal the count in the table. Nothing may be silently dropped."""
    print("\n[1] EVERY EVENT REACHES THE DIGEST")
    import tempfile, shutil
    tmp = tempfile.mkdtemp(prefix="swe_digest_")
    try:
        db, con = _fixture_db(tmp)
        text = canon_digest.render(con, "r1", "fixture")
        n_db = con.execute("SELECT COUNT(*) FROM events WHERE run_id='r1'").fetchone()[0]
        n_txt = sum(1 for l in text.split("\n") if l.startswith("- **["))
        print("       db=%d  digest=%d" % (n_db, n_txt))
        check("counts-agree", n_db == n_txt, "db %d vs digest %d" % (n_db, n_txt))
        check("each-event-type-appears", all(t in text for t in ("betray", "threat", "care")))
        check("the-scene-label-attributes-the-event", "the yard" in text)
        check("the-header-states-non-authoritative", "Non-authoritative" in text)
        check("and-names-the-run", "r1" in text)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_empty_says_empty_rather_than_rendering_nothing():
    """A run with no events must SAY so.

    The distinction between EMPTY and UNBUILT is the one every silent-drop defect in this repo has
    blurred — a blank section reads as 'the tool did not run', which is how a real absence gets
    mistaken for a broken pipeline and vice versa.
    """
    print("\n[2] EMPTY IS STATED, NOT IMPLIED")
    import tempfile, shutil
    tmp = tempfile.mkdtemp(prefix="swe_digest_")
    try:
        db = os.path.join(tmp, "e.db")
        con = connect(db)
        con.execute("INSERT INTO runs(run_id, created_at, status, config) VALUES(?,?,?,?)",
                    ("r0", "2026-01-01", "parked", "{}"))
        con.commit()
        text = canon_digest.render(con, "r0", "fixture")
        check("empty-log-is-named", "EMPTY" in text, text[:200])
        check("every-fold-kind-still-appears",
              all(k.capitalize() in text for k in canon_digest._FOLD_KINDS),
              [k for k in canon_digest._FOLD_KINDS if k.capitalize() not in text])
        check("absent-kinds-say-none-recorded", "(none recorded)" in text)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_render_is_pure():
    """Same DB, same run, same bytes — or 'regenerate from the DB' is not a safe instruction."""
    print("\n[3] REGENERATION IS DETERMINISTIC")
    import tempfile, shutil
    tmp = tempfile.mkdtemp(prefix="swe_digest_")
    try:
        db, con = _fixture_db(tmp)
        a = canon_digest.render(con, "r1", "fixture")
        b = canon_digest.render(con, "r1", "fixture")
        check("two-renders-are-identical", a == b)
        check("it-does-not-narrate",
              "something happened" in a and "story" not in a.lower().split("## event log")[0])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def test_the_docs_promise_is_now_kept():
    """The defect this closes: eight files said GENERATED and no code generated it."""
    print("\n[4] THE PROMISE HAS A PRODUCER")
    hits = []
    for root in ("docs", ".claude", "runs/_TEMPLATE"):
        d = os.path.join(REPO, root)
        for dirpath, _dirs, files in os.walk(d):
            for f in files:
                if f.endswith(".md"):
                    p = os.path.join(dirpath, f)
                    if "canon-ledger" in io.open(p, encoding="utf-8", errors="replace").read():
                        hits.append(os.path.relpath(p, REPO))
    print("       %d doc(s) reference canon-ledger" % len(hits))
    check("docs-still-reference-it", bool(hits))
    check("and-a-generator-exists", os.path.isfile(os.path.join(REPO, "scripts", "canon_digest.py")))
    check("render-is-importable-and-callable", callable(canon_digest.render))


def main():
    print("test_canon_digest.py — the digest equals the DB it digests")
    for t in (test_every_event_reaches_the_digest, test_empty_says_empty_rather_than_rendering_nothing,
              test_render_is_pure, test_the_docs_promise_is_now_kept):
        t()
    print("\nVERDICT: %s" % ("PASS" if not _FAILS else "FAIL -> %s" % _FAILS))
    return 1 if _FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
