"""The deterministic game engine — the compute half of the compute/generate split (design.md).

Every value is computed here; every word is generated by the LLM layer. The two never swap jobs.
Modules land gate-by-gate: db/records/ledger (g1), state (g2), scene (g3), consolidation (g4), direction (g5).
"""
