"""canon_digest.py — regenerate a book's canon-ledger.md from the run DB it digests.

WHY THIS EXISTS. Eight tracked files describe `canon-ledger.md` as GENERATED — `docs/orchestration.md`
("a generated, human-readable view of the run DB's event log + folded now"), `docs/design.md`,
`CLAUDE.md`'s canon-vs-process split, `.claude/agents/showrunner.md`, and the template's own header —
and until 2026-08-24 nothing generated it. `runs/_TEMPLATE/canon-ledger.md` shipped with
`<!-- one line per canonized event -->` placeholders that no producer ever filled.

That is this repo's dominant defect class: specified, described as built, reaching nothing. The same
shape as `verdict_for` (memorialized in `scripts/scene.py`), `bible.drifted()` (zero callers until
this week), and `formative.*`. A doc that says "generated" is a promise; the generator is the payment.

WHAT IT IS AND IS NOT. Non-authoritative, by CLAUDE.md's rule: the run DB is world-truth canon, this
is a human-readable digest of it. Read it; never cite it in place of the DB. It is regenerated whole
rather than appended to, because the DB is append-only so a full render is always correct, and an
incremental writer would need position state — a ninth duplicate of something the log already knows.

It renders. It does not narrate: payload fields are shown as recorded, never summarised into prose,
because a digest that paraphrases is a second source that can disagree with the first.
"""
import argparse
import io
import json
import os
import sqlite3
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from src.engine import books                                    # noqa: E402

# The kinds `world-state-ledger.md` names, in the template's order. A kind with no rows renders as
# an explicit "(none recorded)" rather than vanishing — a reader must be able to tell EMPTY from
# UNBUILT, which is the distinction every silent-drop defect in this repo has blurred.
_FOLD_KINDS = ("agents", "holdings", "information", "relationships", "tensions", "clock")


def _q(con, sql, args=()):
    con.row_factory = sqlite3.Row
    return con.execute(sql, args).fetchall()


def _latest_run(con):
    rows = _q(con, "SELECT run_id FROM runs ORDER BY rowid DESC LIMIT 1")
    return rows[0]["run_id"] if rows else None


def _scene_labels(con, run_id):
    """turn -> scene label, so an event can say which scene it belongs to."""
    try:
        rows = _q(con, "SELECT scene_no, label, start_turn, end_turn FROM scenes "
                       "WHERE run_id=? ORDER BY scene_no", (run_id,))
    except sqlite3.OperationalError:
        return []                                               # a DB predating the scenes table
    return [dict(r) for r in rows]


def _scene_for(turn, scenes):
    for s in scenes:
        if s["start_turn"] <= turn <= s["end_turn"]:
            return s
    return None


def _payload_bits(raw):
    """The recorded fields, shown as recorded. No paraphrase."""
    try:
        p = json.loads(raw) if isinstance(raw, str) else (raw or {})
    except (ValueError, TypeError):
        return str(raw)[:120]
    if not isinstance(p, dict):
        return str(p)[:120]
    bits = []
    for k in ("text", "summary", "subject", "durability"):
        v = p.get(k)
        if v:
            bits.append("%s=%s" % (k, str(v)[:90]))
    dims = p.get("dimensions")
    if isinstance(dims, dict) and dims:
        bits.append("dimensions=%s" % ", ".join(sorted(dims)))
    return " · ".join(bits) if bits else "(no payload fields)"


def render(con, run_id, slug):
    """The DB -> the digest text. Pure: same DB, same run, same bytes."""
    scenes = _scene_labels(con, run_id)
    events = _q(con, "SELECT event_id, turn, type, actor, target, location, visibility, payload "
                     "FROM events WHERE run_id=? ORDER BY turn, event_id", (run_id,))
    turns = _q(con, "SELECT COUNT(*) c FROM turns WHERE run_id=?", (run_id,))[0]["c"]
    as_of = _q(con, "SELECT MAX(as_of_turn) m FROM snapshots WHERE run_id=?", (run_id,))[0]["m"]

    out = ["# Canon Digest — %s" % slug, ""]
    out.append("> GENERATED by `scripts/canon_digest.py` from the run DB. **Non-authoritative** — the")
    out.append("> DB is world-truth canon (`src/engine/ledger.py`); this is a reading surface. Never")
    out.append("> cite it in place of the DB, and never hand-author facts here: the next regeneration")
    out.append("> overwrites them without asking.")
    out.append(">")
    out.append("> run `%s` · %d turn(s) committed · %d event(s) · %d scene(s)"
               % (run_id, turns, len(events), len(scenes)))
    out.append("")

    out.append("## Event log (digest of the DB's events table)")
    out.append("")
    if not events:
        out.append("*The log is EMPTY — this run has committed no events. That is a fact about the")
        out.append("run, not a missing digest.*")
    else:
        for e in events:
            sc = _scene_for(e["turn"], scenes)
            where = e["location"] or (sc["label"] if sc else "—")
            who = e["actor"] or "—"
            at = "turn %d" % e["turn"] + (" · scene %d %s" % (sc["scene_no"], sc["label"]) if sc else "")
            out.append("- **[%s]** `%s` — %s · %s · *%s* · %s"
                       % (e["event_id"], e["type"], who, at, where, _payload_bits(e["payload"])))
    out.append("")

    out.append("## Folded now (digest of the snapshot, as of turn: %s)"
               % ("—" if as_of is None else as_of))
    out.append("")
    out.append("*A pure fold of the log above (`docs/world-state-ledger.md`). Derived, never authored.*")
    out.append("")
    for kind in _FOLD_KINDS:
        rows = _q(con, "SELECT key, value FROM snapshots WHERE run_id=? AND kind=? AND as_of_turn=? "
                       "ORDER BY key", (run_id, kind, as_of)) if as_of is not None else []
        out.append("- **%s:**" % kind.capitalize())
        if not rows:
            out.append("  - *(none recorded)*")
            continue
        for r in rows:
            try:
                v = json.loads(r["value"])
            except (ValueError, TypeError):
                v = r["value"]
            out.append("  - `%s` — %s" % (r["key"], json.dumps(v, sort_keys=True)[:160]))
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--book", required=True, help="book slug under $SWE_BOOKS, or a path")
    ap.add_argument("--run", default=None, help="run_id (default: the most recent run in the db)")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing the file")
    ap.add_argument("--db", default=None, help="chronicle db path (default: books.db_path(book))")
    args = ap.parse_args()

    try:
        book_dir = books.resolve(args.book)
    except books.BookError as e:
        raise SystemExit(str(e))
    # DERIVED, not re-spelled. This was `os.path.basename(...)` with no lowercasing and no
    # space-substitution, so a book whose folder name is not already its slug could never be
    # digested — it looked for a file that cannot exist and exited "nothing to digest". Three
    # sibling scripts carried a second, differently-written copy of the same derivation.
    slug = books.slug(book_dir)
    db = args.db or books.db_path(book_dir)
    if not os.path.isfile(db):
        raise SystemExit("no chronicle at %s — nothing to digest" % db)

    con = sqlite3.connect(db)
    run_id = args.run or _latest_run(con)
    if run_id is None:
        raise SystemExit("%s holds no runs" % db)
    text = render(con, run_id, slug)

    if args.stdout:
        sys.stdout.write(text)
        return 0
    dest_dir = os.path.join(book_dir, "production")
    if not os.path.isdir(dest_dir):
        dest_dir = book_dir
    dest = os.path.join(dest_dir, "canon-ledger.md")
    io.open(dest, "w", encoding="utf-8", newline="").write(text)
    print("wrote %s (%d chars, run %s)" % (dest, len(text), run_id))
    return 0


if __name__ == "__main__":
    sys.exit(main())
